name: needle_handover-40

shape_meta: &shape_meta
  obs:
    image:
      shape: [84, 84, 3]
      type: rgb
    wrist_image_right:
      shape: [84, 84, 3]
      type: rgb
    wrist_image_left:
      shape: [84, 84, 3]
      type: rgb
    joint_pos:
      shape: [16]
      type: low_dim
  action:
    shape: [14]

env_runner:
  _target_: diffusion_policy.env_runner.orbit_runner.OrbitRunner
  n_train: 20
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}

dataset:
  _target_: diffusion_policy.dataset.orbit_dataset.OrbitImageDataset
  zarr_path: /ACT_Training/liver_needle_handover/2024-09-05-liver_handover.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  shape_meta: *shape_meta
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 40
