name: orbit_needlelift

shape_meta: &shape_meta
  obs:
    image:
      shape: [3, 84, 84]
      type: rgb
    wrist_image_right:
      shape: [3, 84, 84]
      type: rgb
    wrist_image_left:
      shape: [3, 84, 84]
      type: rgb
    joint_pos:
      shape: [16]
      type: low_dim
  action:
    shape: [14]

env_runner:
  _target_: diffusion_policy.env_runner.orbit_runner.OrbitRunner
  n_train: 20
  max_steps: 250
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}

dataset:
  _target_: diffusion_policy.dataset.orbit_dataset.OrbitImageDataset
  zarr_path: /media/m2/holoscan-dev/holoscan-ml/robots/orbit-surgical-nv/logs/act/new_data.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  shape_meta: *shape_meta
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 5
